set shell := ["nu", "-c"]

images:
    ls | \
    get name | \
    filter {|it| $it | str ends-with "png" | str starts-with "Screenshot"} | \
    each {|x| mv $x ($x | str substring 25.. | str trim)}
    @echo "Finished"

# convert copied images to have similar backgorund to page color bg
convert:
    ls | \
     where ($it.name | str ends-with ".png") | \
     select name | \
     insert path-segs {|it| $it.name | path parse} | \
     flatten |\
     insert command { \
        |it| convert ($it.name) -fill '#f9f9f9' -opaque white -flatten ({parent: $it.parent, stem: ($it.stem + ".bg"), extension: $it.extension}  | path join) \
     }